apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: true
    isDefault: true
    editable: true
    basicAuthUser: prometheus
    basicAuthPassword: Prometheus