name: test-code-examples

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  workshop:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: run integration tests
        timeout-minutes: 60
        working-directory: code-examples
        env:
          NODE_OPTIONS: --unhandled-rejections=strict
          FAUCET_SEED: ${{ secrets.PEREGRINE_FAUCET_SEED }}
        run: |
          yarn install --frozen
          yarn run ts-node run_workshop.ts

  core_features:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: run integration tests
        timeout-minutes: 60
        working-directory: code-examples
        env:
          NODE_OPTIONS: --unhandled-rejections=strict
          FAUCET_SEED: ${{ secrets.PEREGRINE_FAUCET_SEED }}
        run: |
          yarn install --frozen
          yarn run ts-node run_core_features.ts

 run_getting-started:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: run getting started tests
        timeout-minutes: 60
        working-directory: code-examples

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: run getting started
        timeout-minutes: 10
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: kilt/prototype-chain
        run: |
          docker pull $ECR_REGISTRY/$ECR_REPOSITORY:latest-rc
          docker run -d --rm -p 9944:9944 $ECR_REGISTRY/$ECR_REPOSITORY:latest-rc --dev --ws-port 9944 --ws-external
          sleep 5s
          yarn run ts-node getting_started/getting-started.ts
          docker stop $(docker ps -f ancestor=$ECR_REGISTRY/$ECR_REPOSITORY:latest-rc -q)
